image: gradle:jdk8

stages:
  - test
  - coverage

executeTests:
  stage: test
  script:
    - gradle test
  artifacts:
    reports:
      junit: ./build/test-results/test/TEST-*.xml
  cache:
    untracked: true

testCoverage:
  stage: coverage
  script:
    - gradle jacocoTestReport
    - gradle printCoverage
  coverage: '/^Coverage:\s(\d+\.\d+%)/'
  artifacts:
    name: 'coverageReport'
    paths:
      - build/jacocoHtml
  cache:
    untracked: true
